# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            utilForever's Programming Life!
tagline:          'A Jekyll theme'
description:      'Momenti Engine Engineer, Microsoft Developer Technologies MVP, C++ Korea Founder and Reinforcement Learning KR Administrator'
url:              http://utilForever.github.io

author:
  name:           'Chris Ohk'
  url:            https://twitter.com/utilForever

paginate:         5

# Custom vars
version:          1.0

github:
  repo:           https://github.com/utilForever

# Dependencies
plugins:          [jekyll-gist, jekyll-feed, jekyll-paginate]

# Disqus Comments
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: utilforevers-programming-life