# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            utilForever's Programming Life!
tagline:          'A Jekyll theme'
description:      'Nexon Korea Game Programmer, Microsoft Developer Technologies MVP, C++ Korea Group Administrator'
url:              http://utilForever.github.io

author:
  name:           'Chris Ohk'
  url:            https://twitter.com/utilForever

paginate:         5

# Custom vars
version:          1.0

github:
  repo:           https://github.com/utilForever

# Dependencies
plugins:          [jekyll-gist, jekyll-feed, jekyll-paginate, redcarpet]